server:
  port: ${PORT:5001}
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    tomcat:
      max-wait: 10000
      max-active: 10
  redis:
    url: ${REDIS_URL}
    pool:
      max-active: 10
      max-idle: 5
      min-idle: 1